version: 2.1

executors:
  default:
    docker:
      - image: hashicorp/terraform:0.11.13
    working_directory: ~/project

commands:
  terraform_fmt:
    steps:
      - run:
          name: "terraform fmt"
          command: |
              terraform fmt -diff=true -check=true

  terraform_plan:
    steps:
      - run:
          name: "terraform init"
          command: |
            mkdir -p $HOME/$ENVIRONMENT_DIRECTORY
            echo $GCP_CREDENTIALS | base64 -d > $HOME/$ENVIRONMENT_DIRECTORY/gcp_credentials.json
            echo 'export GOOGLE_APPLICATION_CREDENTIALS="$HOME/$ENVIRONMENT_DIRECTORY/gcp_credentials.json"' >> $BASH_ENV
            source $BASH_ENV
            cd gmail/terraform/gcp/pubsub/$ENVIRONMENT_DIRECTORY
            terraform init -backend-config backend.tfvars ../
      - run:
          name: "terraform plan"
          command: |
            source $BASH_ENV
            cd gmail/terraform/gcp/pubsub/$ENVIRONMENT_DIRECTORY
            terraform plan ../

  terraform_apply:
    steps:
      - run:
          name: "terraform init"
          command: |
            mkdir -p $HOME/$ENVIRONMENT_DIRECTORY
            echo $GCP_CREDENTIALS | base64 -d > $HOME/$ENVIRONMENT_DIRECTORY/gcp_credentials.json
            echo 'export GOOGLE_APPLICATION_CREDENTIALS="$HOME/$ENVIRONMENT_DIRECTORY/gcp_credentials.json"' >> $BASH_ENV
            source $BASH_ENV
            cd gmail/terraform/gcp/pubsub/$ENVIRONMENT_DIRECTORY
            terraform init -backend-config backend.tfvars ../
      - run:
          name: "terraform apply"
          command: |
            source $BASH_ENV
            cd gmail/terraform/gcp/pubsub/$ENVIRONMENT_DIRECTORY
            terraform apply --auto-approve ../

jobs:
  build:
    executor: default
    steps:
      - checkout
      - terraform_fmt

  plan: &plan
    executor: default
    steps:
      - checkout
      - terraform_plan
  plan-dev:
    <<: *plan
  plan-stg:
    <<: *plan
  plan-prd:
    <<: *plan

  apply: &apply
    executor: default
    steps:
      - checkout
      - terraform_apply
  apply-dev:
    <<: *apply
  apply-stg:
    <<: *apply
  apply-prd:
    <<: *apply

################################################################
# CircleCIのContextsを利用し、環境毎の認証情報等をセットする
# セットされている値
# - GCP_CREDENTIALS: service accountのjsonをbase64でエンコードした値
# - ENVIRONMENT_DIRECTORY: terraform の環境ディレクトリ名
################################################################
workflows:
  version: 2
  build_plan_apply:
    jobs:
      - build
      # dev
      - plan-dev:
          context: gmail-dev
          requires:
            - build
      # stg
      - plan-stg:
          context: gmail-stg
          requires:
            - build
      # prd
      - plan-prd:
          context: gmail-prd
          requires:
            - build
      # dev
      - apply-dev:
          context: gmail-dev
          requires:
            - plan-dev
          filters:
            branches:
              only: /^release/gmail/dev$/
      # stg
      - apply-stg:
          context: gmail-stg
          requires:
            - plan-stg
          filters:
            branches:
              only: /^release/gmail/stg$/
      # prd
      - approve:
          type: approval
          requires:
            - plan-prd
          filters:
            branches:
              only: /^release/gmail/prd$/
      - apply-prd:
          context: gmail-prd
          requires:
            - approve
          filters:
            branches:
              only: /^release/gmail/prd$/

#      - plan-prd:
#          context: gmail-prd
#          requires:
#            - build
#      # ブランチ名 release/<project>/<environment> にマージされた時にterraform applyを実行する
#      - apply-dev:
#          context: gmail-dev
#          filters:
#            branches:
#              only: /^release/gmail/dev$/
#      - apply-stg:
#          context: gmail-stg
#          filters:
#            branches:
#              only: /^release/gmail/stg$/
#      - apply-prd:
#          context: gmail-prd
#          filters:
#            branches:
#              only: /^release/gmail/prd$/
