version: 2.1

executors:
  default:
    docker:
      - image: hashicorp/terraform:0.11.13
    working_directory: ~/project

commands:
  install_dependency_package:
    steps:
      - run:
          name: "install dependency package"
          command: |
            apk add bash tar gzip

  install_tfnotify:
    steps:
      - run:
          name: "install tfnotify"
          command: |
            ./scripts/install-tfnotify.sh

  terraform_fmt:
    steps:
      - run:
          name: "terraform fmt"
          command: |
            ./scripts/tf-fmt.sh

  terraform_validate:
    steps:
      - run:
          name: "terraform init"
          command: |
            ./scripts/tf-init.sh
      - run:
          name: "terraform validate"
          command: |
            ./scripts/tf-validate.sh

  terraform_plan:
    steps:
      - run:
          name: "terraform init"
          command: |
            ./scripts/tf-init.sh
      - run:
          name: "terraform plan"
          command: |
            ./scripts/tf-plan.sh

  terraform_apply:
    steps:
      - run:
          name: "terraform init"
          command: |
            ./scripts/tf-init.sh
      - run:
          name: "terraform apply"
          command: |
            ./scripts/tf-apply.sh

jobs:
  build: &build
    executor: default
    steps:
      - checkout
      - install_dependency_package
      - install_tfnotify
      - terraform_fmt
      - terraform_plan
  build-dev:
    <<: *build
  build-stg:
    <<: *build
  build-prd:
    <<: *build

  deploy: &deploy
    executor: default
    steps:
      - checkout
      - install_dependency_package
      - install_tfnotify
      - terraform_apply
  deploy-dev:
    <<: *deploy
  deploy-stg:
    <<: *deploy
  deploy-prd:
    <<: *deploy

######################################################################################
# 1. CircleCIのContextsを利用し、環境毎の認証情報等をセットする
# - GCP_CREDENTIALS: service accountのjsonをbase64でエンコードした値
# - ENVIRONMENT_DIRECTORY: terraform の環境ディレクトリ名
# 2. ブランチ名 release/<project>/<environment> にマージされた時にterraform applyを実行する
######################################################################################
workflows:
  version: 2
  build_and_deploy:
    jobs:
      # dev
      - build-dev:
          context: gmail-dev
      # stg
      - build-stg:
          context: gmail-stg
      # prd
      - build-prd:
          context: gmail-prd
      # dev
      - deploy-dev:
          context: gmail-dev
          requires:
            - build-dev
          filters:
            branches:
              only: /^release/gmail/dev$/
      # stg
      - deploy-stg:
          context: gmail-stg
          requires:
            - build-stg
          filters:
            branches:
              only: /^release/gmail/stg$/
      # prd
      - approve:
          type: approval
          requires:
            - build-prd
          filters:
            branches:
              only: /^release/gmail/prd$/
      - deploy-prd:
          context: gmail-prd
          requires:
            - approve
          filters:
            branches:
              only: /^release/gmail/prd$/
