version: 2.1

executors:
  default:
    docker:
      - image: hashicorp/terraform:0.11.13
    working_directory: &working_directory
      ~/project

commands:
  install_dependency_package:
    steps:
      - run:
          name: "install dependency package"
          command: |
            apk add bash tar gzip grep

  install_tfnotify:
    steps:
      - run:
          name: "install tfnotify"
          command: |
            ./scripts/install-tfnotify.sh

  terraform_fmt:
    steps:
      - run:
          name: "terraform fmt"
          command: |
            ./scripts/tf-fmt.sh

  terraform_validate:
    steps:
      - run:
          name: "terraform validate"
          command: |
            ./scripts/tf-init.sh
            ./scripts/tf-validate.sh

  terraform_plan:
    steps:
      - run:
          name: "terraform plan"
          command: |
            ./scripts/tf-init.sh
            ./scripts/tf-plan.sh

  terraform_apply:
    steps:
      - run:
          name: "terraform apply"
          command: |
            ./scripts/tf-init.sh
            ./scripts/tf-apply.sh

############################################
# jobs
############################################
jobs:
  ############################################
  # build
  ############################################
  build: &build
    executor: default
    steps:
      - checkout
      - install_dependency_package
      - install_tfnotify
      - terraform_fmt
      - terraform_validate
  # movies-stg
  build-movies-stg:
    <<: *build
  # movies-prd
  build-movies-prd:
    <<: *build
  # payment-stg
  build-payment-stg:
    <<: *build
  # payment-prd
  build-payment-prd:
    <<: *build
  ############################################
  # plan
  ############################################
  plan: &plan
    executor: default
    steps:
      - checkout
      - install_dependency_package
      - install_tfnotify
      - terraform_plan
      - persist_to_workspace:
          root: *working_directory
          paths:
            - ./terraform
  # movies-stg
  plan-movies-stg:
    <<: *plan
  # movies-prd
  plan-movies-prd:
    <<: *plan
  # payment-stg
  plan-payment-stg:
    <<: *plan
  # payment-prd
  plan-payment-prd:
    <<: *plan
  ############################################
  # apply
  ############################################
  apply: &apply
    executor: default
    steps:
      - checkout
      - install_dependency_package
      - install_tfnotify
      - attach_workspace:
          at: *working_directory
      - terraform_apply
  # movies-stg
  apply-movies-stg:
    <<: *apply
  # movies-prd
  apply-movies-prd:
    <<: *apply
  # payment-stg
  apply-payment-stg:
    <<: *apply
  # payment-prd
  apply-payment-prd:
    <<: *apply

############################################
# workflows
############################################
workflows:
  version: 2
  build_plan_apply:
    jobs:
      ############################################
      # build
      ############################################
      # movies-stg
      - build-movies-stg:
          context: movies-stg
      # movies-prd
      - build-movies-prd:
          context: movies-prd
      # payment-stg
      - build-payment-stg:
          context: payment-stg
      # payment-prd
      - build-payment-prd:
          context: payment-prd
      ############################################
      # plan
      ############################################
      # movies-stg
      - plan-movies-stg:
          context: movies-stg
          requires:
            - build-movies-stg
      # movies-prd
      - plan-movies-prd:
          context: movies-prd
          requires:
            - build-movies-prd
      # payment-stg
      - plan-payment-stg:
          context: payment-stg
          requires:
            - build-payment-stg
      # payment-prd
      - plan-payment-prd:
          context: payment-prd
          requires:
            - build-payment-prd
      ############################################
      # apply
      ############################################
      # movies-stg
      - apply-movies-stg:
          context: movies-stg
          requires:
            - plan-movies-stg
          filters:
            branches:
              only: /^release/movies/stg$/
      # movies-prd
      - approve-movies-prd:
          type: approval
          requires:
            - plan-movies-prd
          filters:
            branches:
              only: /^release/movies/prd$/
      - apply-movies-prd:
          context: movies-prd
          requires:
            - approve-movies-prd
          filters:
            branches:
              only: /^release/movies/prd$/
      # payment-stg
      - apply-payment-stg:
          context: payment-stg
          requires:
            - plan-payment-stg
          filters:
            branches:
              only: /^release/payment/stg$/
      # payment-prd
      - approve-payment-prd:
          type: approval
          requires:
            - plan-payment-prd
          filters:
            branches:
              only: /^release/payment/prd$/
      - apply-payment-prd:
          context: payment-prd
          requires:
            - approve-payment-prd
          filters:
            branches:
              only: /^release/payment/prd$/
