version: 2.1

executors:
  default:
    docker:
      - image: hashicorp/terraform:0.11.13
    working_directory: ~/project

commands:
  install_dependency_package:
    steps:
      - run:
          name: "install dependency package"
          command: |
            apk add bash tar gzip

  install_tfnotify:
    steps:
      - run:
          name: "install tfnotify"
          command: |
            ./scripts/install-tfnotify.sh

  terraform_fmt:
    steps:
      - run:
          name: "terraform fmt"
          command: |
            ./scripts/tf-fmt.sh

  terraform_plan:
    steps:
      - run:
          name: "terraform init"
          command: |
            mkdir -p $HOME/$ENVIRONMENT_DIRECTORY
            echo $GCP_CREDENTIALS | base64 -d > $HOME/$ENVIRONMENT_DIRECTORY/gcp_credentials.json
            echo 'export GOOGLE_APPLICATION_CREDENTIALS="$HOME/$ENVIRONMENT_DIRECTORY/gcp_credentials.json"' >> $BASH_ENV
            source $BASH_ENV
            ./scripts/tf-init.sh

      - run:
          name: "terraform plan"
          command: |
            source $BASH_ENV
            ./scripts/tf-plan.sh

  terraform_apply:
    steps:
      - run:
          name: "terraform init"
          command: |
            mkdir -p $HOME/$ENVIRONMENT_DIRECTORY
            echo $GCP_CREDENTIALS | base64 -d > $HOME/$ENVIRONMENT_DIRECTORY/gcp_credentials.json
            echo 'export GOOGLE_APPLICATION_CREDENTIALS="$HOME/$ENVIRONMENT_DIRECTORY/gcp_credentials.json"' >> $BASH_ENV
            source $BASH_ENV
            ./scripts/tf-init.sh
      - run:
          name: "terraform apply"
          command: |
            source $BASH_ENV
            ./scripts/tf-apply.sh

jobs:
  build:
    executor: default
    steps:
      - checkout
      - install_dependency_package
      - terraform_fmt

  plan: &plan
    executor: default
    steps:
      - checkout
      - install_dependency_package
      - install_tfnotify
      - terraform_plan
  plan-dev:
    <<: *plan
  plan-stg:
    <<: *plan
  plan-prd:
    <<: *plan

  apply: &apply
    executor: default
    steps:
      - checkout
      - install_dependency_package
      - install_tfnotify
      - terraform_apply
  apply-dev:
    <<: *apply
  apply-stg:
    <<: *apply
  apply-prd:
    <<: *apply

################################################################
# 1. CircleCIのContextsを利用し、環境毎の認証情報等をセットする
# - GCP_CREDENTIALS: service accountのjsonをbase64でエンコードした値
# - ENVIRONMENT_DIRECTORY: terraform の環境ディレクトリ名
# 2. ブランチ名 release/<project>/<environment> にマージされた時にterraform applyを実行する
################################################################
workflows:
  version: 2
  build_plan_apply:
    jobs:
      - build
      # dev
      - plan-dev:
          context: gmail-dev
          requires:
            - build
      # stg
      - plan-stg:
          context: gmail-stg
          requires:
            - build
      # prd
      - plan-prd:
          context: gmail-prd
          requires:
            - build
      # dev
      - apply-dev:
          context: gmail-dev
          requires:
            - plan-dev
          filters:
            branches:
              only: /^release/gmail/dev$/
      # stg
      - apply-stg:
          context: gmail-stg
          requires:
            - plan-stg
          filters:
            branches:
              only: /^release/gmail/stg$/
      # prd
      - approve:
          type: approval
          requires:
            - plan-prd
          filters:
            branches:
              only: /^release/gmail/prd$/
      - apply-prd:
          context: gmail-prd
          requires:
            - approve
          filters:
            branches:
              only: /^release/gmail/prd$/
