version: 2

jobs:
  terraform:
    docker:
      - image: hashicorp/terraform:0.11.13
    steps:
      - checkout
      - run:
          name: "terraform init dev"
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 -d > $HOME/gcp_credentials.json
            echo 'export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcp_credentials.json"' >> $BASH_ENV
            source $BASH_ENV
            tree
            cd gmail/terraform/gcp/pubsub/develop
            terraform init -backend-config backend.tfvars ../
      - run:
          name: terraform plan
          command: |
            source $BASH_ENV
            cd gmail/terraform/gcp/pubsub/develop
            terraform plan ../
