version: 2.1

executors:
  default:
    docker:
      - image: hashicorp/terraform:0.11.13
    working_directory: ~/project

commands:
  install_dependency_package:
    steps:
      - run:
          name: "install dependency package"
          command: |
            apk add bash tar gzip

  install_tfnotify:
    steps:
      - run:
          name: "install tfnotify"
          command: |
            ./scripts/install-tfnotify.sh

  terraform_fmt:
    steps:
      - run:
          name: "terraform fmt"
          command: |
            ./scripts/tf-fmt.sh

  terraform_validate:
    steps:
      - run:
          name: "terraform init"
          command: |
            ./scripts/tf-init.sh
      - run:
          name: "terraform validate"
          command: |
            ./scripts/tf-validate.sh

  terraform_plan:
    steps:
      - run:
          name: "terraform init"
          command: |
            ./scripts/tf-init.sh
      - run:
          name: "terraform plan"
          command: |
            ./scripts/tf-plan.sh

  terraform_apply:
    steps:
      - run:
          name: "terraform init"
          command: |
            ./scripts/tf-init.sh
      - run:
          name: "terraform apply"
          command: |
            ./scripts/tf-apply.sh

############################################
# jobs
############################################
jobs:
  ############################################
  # build
  ############################################
  build: &build
    executor: default
    steps:
      - checkout
      - install_dependency_package
      - install_tfnotify
      - terraform_fmt
      - terraform_plan
  # movies
  build-movies-stg:
    <<: *build
  build-movies-prd:
    <<: *build
  # payment
  build-payment-stg:
    <<: *build
  build-payment-prd:
    <<: *build
  ############################################
  # deploy
  ############################################
  deploy: &deploy
    executor: default
    steps:
      - checkout
      - install_dependency_package
      - install_tfnotify
      - terraform_apply
  # movies
  deploy-movies-stg:
    <<: *deploy
  deploy-movies-prd:
    <<: *deploy
  # payment
  deploy-payment-stg:
    <<: *deploy
  deploy-payment-prd:
    <<: *deploy

############################################
# workflows
############################################
workflows:
  version: 2
  build_and_deploy:
    jobs:
      ############################################
      # build
      ############################################
      # movies-stg
      - build-movies-stg:
          context: movies-stg
      # movies-prd
      - build-movies-prd:
          context: movies-prd
      # payment-stg
      - build-payment-stg:
          context: payment-stg
      # payment-prd
      - build-payment-prd:
          context: payment-prd
      ############################################
      # deploy
      ############################################
      # movies-stg
      - deploy-movies-stg:
          context: movies-stg
          requires:
            - build-movies-stg
          filters:
            branches:
              only: /^release/movies/stg$/
      # movies-prd
      - approve-movies-prd:
          type: approval
          requires:
            - build-movies-prd
          filters:
            branches:
              only: /^release/moives/prd$/
      - deploy-movies-prd:
          context: movies-prd
          requires:
            - approve-movies-prd
          filters:
            branches:
              only: /^release/movies/prd$/
      # payment-stg
      - deploy-payment-stg:
          context: payemnt-stg
          requires:
            - build-payment-stg
          filters:
            branches:
              only: /^release/payemnt/stg$/
      # payment-prd
      - approve-payment-prd:
          type: approval
          requires:
            - build-payment-prd
          filters:
            branches:
              only: /^release/payment/prd$/
      - deploy-payment-prd:
          context: payemnt-prd
          requires:
            - approve-payment-prd
          filters:
            branches:
              only: /^release/payment/prd$/
