version: 2
jobs:
  terraform_fmt:
    docker:
      - image: hashicorp/terraform:0.11.13
    working_directory: ~/my_project
    steps:
      - checkout
      - run:
          name: "terraform fmt"

workflows:
  version: 2
  terraform:
    jobs:
      - terraform_fmt
