version: 2.1

executors:
  default:
    docker:
      - image: hashicorp/terraform:0.11.13
    working_directory: ~/my_project

commands:
  setting_up_gcp_credentials:
    steps:
      - run:
          name: "setting up gcp credentials"
          command: |
            echo $GCP_CREDENTIALS | base64 -d > ${HOME}/gcp_credentials.json
            echo 'GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcp_credentials.json"' >> $BASH_ENV

  terraform_fmt:
    steps:
      - run:
          name: "terraform fmt"
          command: terraform fmt -diff=true -check=true

  terraform_init:
    steps:
      - run:
          name: "terraform init"
          command: |
            source $BASH_ENV
            cd terraform/gcp/pubsub
            terraform init

  terraform_plan:
    steps:
      - run:
          name: "terraform plan"
          command: |
            source $BASH_ENV
            cd terraform/gcp/pubsub
            terraform plan

jobs:
  terraform_fmt:
    executor: default
    steps:
      - checkout
      - terraform_fmt

  terraform_plan:
    executor: default
    steps:
      - checkout
      - setting_up_gcp_credentials
      - terraform_init
      - run:
          name: "terraform plan"
          command: |
            source $BASH_ENV
            cd terraform/gcp/pubsub
            terraform plan

  terraform_apply:
    executor: default
    steps:
      - checkout
      - setting_up_gcp_credentials
      - terraform_init
      - run:
          name: "terraform apply"
          command: |
            source $BASH_ENV
            cd terraform/gcp/pubsub
            terraform apply --auto-approve


workflows:
  version: 2
  terraform:
    jobs:
      - terraform_fmt
      - terraform_plan:
          requires:
            - terraform_fmt
      - terraform_apply:
          requires:
            - terraform_plan
