version: 2.1

executors:
  default:
    docker:
      - image: hashicorp/terraform:0.11.13

commands:
  terraform_fmt:
    steps:
      - run:
          name: "terraform fmt"
          command: |
            terraform fmt -diff=true -check=true

  terraform_init:
    steps:
      - run:
          name: "terraform init"
          command: |
            echo $GCP_CREDENTIALS | base64 -d > ${HOME}/gcp_credentials.json
            export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/gcp_credentials.json"
            cd terraform/gcp/pubsub
            terraform init

  terraform_plan:
    steps:
      - run:
          name: "terraform plan"
          command: |
            cd terraform/gcp/pubsub
            terraform plan

jobs:
  terraform_fmt:
    executor: default
    working_directory: ~/my_project
    steps:
      - checkout
      - terraform_fmt
  terraform_plan:
    executor: default
    working_directory: ~/my_project
    steps:
      - checkout
      - terraform_init
      - terraform_plan

workflows:
  version: 2
  terraform:
    jobs:
      - terraform_fmt
      - terraform_plan:
          requires:
            - terraform_fmt
